export const MOVIE_SEARCH_REQUEST = "MOVIE_SEARCH_REQUEST";
export const MOVIE_SEARCH_SUCCESS = "MOVIE_SEARCH_SUCCESS";
export const MOVIE_SEARCH_FAIL = "MOVIE_SEARCH_FAIL";

export const MOVIE_ADD_NOMINATION_REQUEST = "MOVIE_ADD_NOMINATION_REQUEST";
export const MOVIE_ADD_NOMINATION_SUCCESS = "MOVIE_ADD_NOMINATION_SUCCESS";
export const MOVIE_ADD_NOMINATION_FAIL = "MOVIE_ADD_NOMINATION_FAIL";

export const MOVIE_DELETE_NOMINATION_REQUEST =
  "MOVIE_DELETE_NOMINATION_REQUEST";
export const MOVIE_DELETE_NOMINATION_SUCCESS =
  "MOVIE_DELETE_NOMINATION_SUCCESS";
export const MOVIE_DELETE_NOMINATION_FAIL = "MOVIE_DELETE_NOMINATION_FAIL";

export const USER_NOMINATIONS_REQUEST = "USER_NOMINATIONS_REQUEST";
export const USER_NOMINATIONS_SUCCESS = "USER_NOMINATIONS_SUCCESS";
export const USER_NOMINATIONS_FAIL = "USER_NOMINATIONS_FAIL";

export const MOVIE_ADD_NOMINATION = "MOVIE_ADD_NOMINATION";
export const MOVIE_REMOVE_NOMINATION = "MOVIE_REMOVE_NOMINATION";
export const MOVIE_CLEAR_NOMINATION = "MOVIE_CLEAR_NOMINATION";
